### ISSUE TITLE
crash on server fabric 1.14.1-20

### ISSUE THREAD

**Issue by SDUBZ** [Draylar/extra-pressure-plates#3]
got this random crash on my server why digging out dirt 1.14.1 http://puu.sh/DxQJt/cdd8148a23.txt

happening on server side 

using frabric 1.14.1 build 10

**Comment by SDUBZ** [comment]
tested in singplayer too with same world 
[crash-2019-05-27_17.28.37-server.txt](https://github.com/Draylar/extra-pressure-plates/files/3222380/crash-2019-05-27_17.28.37-server.txt)
[latest.log](https://github.com/Draylar/extra-pressure-plates/files/3222381/latest.log)

**Comment by Draylar** [comment]
Fixed in 1.14.2, thanks for the report!
